name: 'gitbook-publish'
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      USER_NAME : sunlight0258
      USER_EMAIL: skysgreen@qq.com
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '10.22.0'
      - run: 
          npm install gitbook-cli -g
      - run:
          gitbook init
      - run:
          gitbook install
      - run:
          mkdir docs
      - run:
          gitbook build ./ --output=. ./docs
      - name: Build
        uses: bob1113/gitbook-publish@v1.0.0

